blank_issues_enabled: false
contact_links:
  - name: ğŸƒ æ—©ãç­”ãˆãŒæ¬²ã—ã„å ´åˆ
    url: https://discord.gg/sH8etgNBy7
    about: |
      Discordã‚µãƒ¼ãƒãƒ¼ã«å‚åŠ ã—ã¦ã€é‹å–¶é™£ã«ç›´æ¥è³ªå•ã‚’ã™ã‚‹ã“ã¨ã§ã‚ˆã‚Šæ—©ãç­”ãˆã‚’å¾—ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚